# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.23.1
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Miniconda3/envs/pythonProject\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Miniconda3/envs/pythonProject\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Miniconda3/envs/pythonProject\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Miniconda3/envs/pythonProject\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Miniconda3/envs/pythonProject\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Miniconda3/envs/pythonProject\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Miniconda3/envs

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
nulVec = np.zeros(10)
nulVec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
#help(np.ndarray)
nulVec.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via t

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
nullVec = np.zeros(10, dtype=np.int64)
nullVec[4] = 1
nullVec

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vec = np.arange(10, 50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [14]:
revers = vec[::-1]
revers

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
matr = np.arange(9).reshape(3, 3)
matr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
arr = np.array([1,2,0,0,4,0])
arr.nonzero()[0]

array([0, 1, 4], dtype=int64)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [17]:
idmatr = np.eye(3)
idmatr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [19]:
arr3 = np.random.random((3,3,3))
arr3

array([[[0.48305522, 0.86044316, 0.52515842],
        [0.11848447, 0.73080725, 0.57092455],
        [0.22152712, 0.01768397, 0.40096797]],

       [[0.7579962 , 0.55122774, 0.28106727],
        [0.46827882, 0.93707133, 0.99978926],
        [0.99581108, 0.79056988, 0.61179833]],

       [[0.92275998, 0.32506243, 0.54364085],
        [0.20665192, 0.2080625 , 0.21756534],
        [0.08970692, 0.02563023, 0.45546229]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
arr10 = np.random.random((10,10))

print(arr10)
print(f"maximum: {arr10.max()} minimum: {arr10.min()}")

[[0.29609841 0.69811147 0.72901453 0.49126332 0.7922421  0.13750791
  0.07840732 0.35283371 0.71119135 0.38832904]
 [0.67302756 0.20611713 0.19935332 0.78705414 0.13161443 0.63443567
  0.31539781 0.60131925 0.9067805  0.92501646]
 [0.05261781 0.02535343 0.34953058 0.14063316 0.282167   0.823612
  0.63444565 0.84159133 0.97633301 0.99555787]
 [0.89620966 0.82842298 0.30615562 0.96314941 0.361587   0.75038226
  0.56383776 0.44534598 0.37091596 0.97270133]
 [0.73471011 0.26665382 0.33027998 0.00955161 0.3390242  0.17787456
  0.67457098 0.39155737 0.38821956 0.72281862]
 [0.43728511 0.06382067 0.97358968 0.77866798 0.05096634 0.2022619
  0.62729641 0.30719203 0.34601093 0.33848444]
 [0.27233304 0.57860759 0.44394977 0.10908401 0.59094551 0.92171399
  0.85454134 0.39727575 0.27860717 0.21930497]
 [0.40376932 0.9832729  0.71435144 0.50644069 0.09396613 0.32620881
  0.12253906 0.0066858  0.82811342 0.93260027]
 [0.85433606 0.74354551 0.26457579 0.39191183 0.85514133 0.87268906
  0.5591503  0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [26]:
vec0 = np.random.random(30)
print(vec0)
mean = np.mean(vec0)
mean

[0.31208358 0.34979749 0.68361358 0.7758824  0.35338771 0.34562298
 0.90438823 0.85855957 0.90531971 0.53797383 0.41064788 0.98288698
 0.39228988 0.34955503 0.37471124 0.56885546 0.34601875 0.20074749
 0.88479143 0.51088068 0.73840587 0.06113487 0.15232389 0.65203026
 0.11517281 0.08723188 0.72472563 0.30877421 0.64617589 0.50294872]


0.5012312636804601

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [27]:
arr2d = np.ones((6, 6), dtype=np.int32)
arr2d[1:-1, 1: -1] = 0
arr2d

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [28]:
from numpy.random._examples.cffi.extending import rng

matr3d = rng.integers(10, 100, size=(3,3))
bordered = np.pad(matr3d, pad_width = 1, constant_values = 0)
bordered

array([[ 0,  0,  0,  0,  0],
       [ 0, 92, 63, 74,  0],
       [ 0, 31, 36, 75,  0],
       [ 0, 93, 46, 41,  0],
       [ 0,  0,  0,  0,  0]], dtype=int64)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [29]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [30]:
matr5x5 = np.diag(np.arange(1,5), k = -1)
matr5x5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [31]:
b = np.zeros((8,8), dtype = np.int32)
b[1::2, ::2] = 1
b[::2, 1::2] = 1
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [32]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [33]:
def f(i, j):
    return (i + j) % 2
b = np.fromfunction(f, (8,8), dtype = np.int8)
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int8)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [35]:
matr0 = rng.integers(100, size=(5,5))
dfmax, dfmin = matr0.max(), matr0.min()
df = (matr0 - dfmin)/(dfmax - dfmin)
print(df)

[[0.53608247 0.8556701  0.65979381 0.03092784 0.25773196]
 [1.         0.51546392 0.86597938 0.43298969 0.37113402]
 [0.39175258 0.69072165 0.54639175 0.50515464 0.91752577]
 [0.88659794 0.         1.         0.91752577 0.26804124]
 [0.77319588 0.97938144 0.28865979 0.97938144 0.89690722]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [38]:
rgbadt = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
img = np.array([(13, 45, 56, 255), (53, 65, 136, 255), (183, 25, 96, 255)], dtype = rgbadt)
img

array([( 13, 45,  56, 255), ( 53, 65, 136, 255), (183, 25,  96, 255)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [39]:
matr5x3 = rng.integers(10, size=(5,3))
print(matr5x3)
matr3x2 = rng.integers(10, size=(3,2))
print(matr3x2)
product = np.matmul(matr5x3, matr3x2)
product

[[9 0 8]
 [5 3 5]
 [6 2 8]
 [6 2 6]
 [3 7 9]]
[[1 3]
 [2 2]
 [4 7]]


array([[41, 83],
       [31, 56],
       [42, 78],
       [34, 64],
       [53, 86]], dtype=int64)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [40]:
ar = np.arange(15)
ar[(ar > 3) & (ar < 8)] = -ar[(ar > 3) & (ar < 8)]
ar

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [41]:
print(sum(range(5),-1)) #9
from numpy import *
print(sum(range(5),-1))  #10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [42]:
Z = np.arange(3)
print(Z**Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z)

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [43]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Xiaomi\AppData\Local\Temp\ipykernel_11804\1729466501.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\Xiaomi\AppData\Local\Temp\ipykernel_11804\1729466501.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [44]:
def roundAwayFromZero(array):
    a = np.abs(array)
    b = np.floor(a) + np.floor(2*(a%1))
    return np.copysign(b, array)

x = np.linspace(-5, 5, 20)
roundAwayFromZero(x)

array([-5., -4., -4., -3., -3., -2., -2., -1., -1., -0.,  0.,  1.,  1.,
        2.,  2.,  3.,  3.,  4.,  4.,  5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [45]:
np.intersect1d([1,2,3,4], [3,5,6,7])

array([3])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [46]:
settings = np.seterr(all='ignore')
np.ones(1) / 0
#np.seterr(**settings)

array([inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [47]:
np.sqrt(-1) == np.emath.sqrt(-1) #first'll return nan and second will return complex number

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [48]:
today = np.datetime64('today', 'D')
tomorrow = today + np.timedelta64(1, 'D')
yesterday = today - np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2022-11-08 2022-11-09 2022-11-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [49]:
dates = np.arange(np.datetime64('2016-07'), np.datetime64('2016-08'), dtype = 'datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [50]:
A = np.ones(3)
B = np.ones(3) * 2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [51]:
x = rng.random(5, dtype=np.double)*10
print(x)
print(x.astype(np.int32))
print(np.trunc(x))
print(np.floor(x))
print(np.fix(x))

[7.39283388 8.70547598 5.09383857 7.70065412 1.64718695]
[7 8 5 7 1]
[7. 8. 5. 7. 1.]
[7. 8. 5. 7. 1.]
[7. 8. 5. 7. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [52]:
x = np.zeros((5,5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [53]:
def generate_integers():
    for i in np.arange(10):
        yield i
np.fromiter(generate_integers(), dtype=np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [54]:
x = np.linspace(0, 1, num=12, endpoint=True)[1:-1]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [55]:
x = rng.random(10)
x.sort()
x

array([0.02777851, 0.10459155, 0.28128978, 0.42731894, 0.61558778,
       0.67989323, 0.8332062 , 0.84283863, 0.84967748, 0.96821318])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [56]:
x = np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [57]:
A = np.random.randint(0, 2, size=5)
B = np.random.randint(0, 2, size=5)
print(A, B)
#Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A, B)
print(equal)
#Checking both the shape and the element values, no tolerance (values have to be exact)
equal = np.array_equal(A,B)
print(equal)

[0 1 0 1 0] [0 0 1 1 1]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [58]:
Z = np.zeros(10)
Z.flags.writeable = False
#Z[0] = 1
print(Z.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False



#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [59]:
Z = np.random.random((10,2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.76194529 0.97305474 0.89792529 0.23580772 1.11861674 0.81056573
 0.84915458 0.66568659 1.2023864  0.86921565]
[0.17955307 0.92551133 0.32164757 1.11484418 0.84605216 0.25814829
 0.30092783 1.54148673 0.6907431  0.48113144]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [60]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.80593438 0.16032418 0.1790315  0.06176423 0.41449641 0.975717
 0.30405173 0.43904023 0.0048568  0.67231237]
[0.80593438 0.16032418 0.1790315  0.06176423 0.41449641 0.
 0.30405173 0.43904023 0.0048568  0.67231237]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [61]:
Z = np.zeros((5,5), [('x', np.float),('y', np.float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


C:\Users\Xiaomi\AppData\Local\Temp\ipykernel_11804\3187766215.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.zeros((5,5), [('x', np.float),('y', np.float)])


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [62]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)
print(np.linalg.det(C))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [63]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [64]:
np.set_printoptions(threshold=256)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [65]:
Z = np.arange(100)
print(Z)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
Z[index]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
69.53368661401606


70

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [66]:
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [67]:
Z = np.random.random((5,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# import scipy
# import scipy.spatial
# D = scipy.spatial.distance.cdist(Z,Z)
# print(D)

[[0.         0.91728332 0.96484258 0.7862137  0.95556506]
 [0.91728332 0.         0.48679266 0.2552141  0.62076129]
 [0.96484258 0.48679266 0.         0.28944924 0.14768924]
 [0.7862137  0.2552141  0.28944924 0.         0.39594698]
 [0.95556506 0.62076129 0.14768924 0.39594698 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [68]:
Z = np.arange(10, dtype=np.float32)
print(Z)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [69]:
from io import StringIO


s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int, filling_values=-1)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\Xiaomi\AppData\Local\Temp\ipykernel_11804\2814181569.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int, filling_values=-1)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [70]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
print()
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [71]:
X, Y = np.meshgrid(np.linspace(-1,1,6), np.linspace(-1,1,6))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.50661699 0.59452055 0.59452055 0.50661699 0.36787944]
 [0.50661699 0.69767633 0.81873075 0.81873075 0.69767633 0.50661699]
 [0.59452055 0.81873075 0.96078944 0.96078944 0.81873075 0.59452055]
 [0.59452055 0.81873075 0.96078944 0.96078944 0.81873075 0.59452055]
 [0.50661699 0.69767633 0.81873075 0.81873075 0.69767633 0.50661699]
 [0.36787944 0.50661699 0.59452055 0.59452055 0.50661699 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [72]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [73]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[ 0.41983191, -0.27819918, -0.19900667, -0.10307547, -0.28400877,
         0.13905721,  0.32397284, -0.33928178,  0.13228118,  0.18842872],
       [ 0.39906716,  0.00393582, -0.44309086, -0.05324688,  0.19302792,
         0.25363136,  0.04603514, -0.41599397, -0.37062414,  0.38725845],
       [-0.24620672,  0.17952631, -0.04997981, -0.40605277,  0.39392934,
        -0.1912115 , -0.18044688, -0.11108526,  0.35004454,  0.26148277],
       [ 0.40500276, -0.32754134,  0.35242453,  0.13061066,  0.51604485,
        -0.37671579, -0.30852221, -0.36365901,  0.13269718, -0.16034163],
       [ 0.47940137, -0.26579847, -0.28495471, -0.2098469 , -0.39983015,
         0.24725609,  0.34026919,  0.48732485, -0.38021425, -0.01360703]])

#### 59. How to sort an array by the nth column? (★★☆)

In [74]:
Z = np.random.randint(0,10,(4,4))
print(Z)
print(Z[Z[:,2].argsort()])

[[8 9 4 9]
 [8 8 5 2]
 [9 1 6 2]
 [9 3 0 5]]
[[9 3 0 5]
 [8 9 4 9]
 [8 8 5 2]
 [9 1 6 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [75]:
Z = np.random.randint(0,3,(3,10))
print(not (Z.any(axis=0).any()))

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [76]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = np.abs(Z - z).argmin()
print(Z[m])

0.5159134445685003


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [77]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [78]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [79]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[4. 3. 5. 2. 1. 2. 3. 1. 5. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [80]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [81]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [82]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[59 60 62 58]
 [64 55 53 56]
 [52 51 59 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [83]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.43826637 0.53849021 0.60690338 0.57396318 0.54369748 0.60084432
 0.380896   0.43084237 0.48765988 0.53386149]


#### 69. How to get the diagonal of a dot product? (★★★)

In [84]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.68330952, 1.85740914, 0.74598355, 1.42330607, 0.63431232])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [85]:
Q = np.array([1,2,3,4,5])
nq = 3
Q0 = np.zeros(len(Q) + (len(Q)-1)*(nq))
Q0[::nq+1] = Q
print(Q0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [86]:
a = np.ones((5,5,3))
b0 = 2*np.ones((5,5))
print(a * b0[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [87]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [88]:
triangle = np.random.randint(0,100,(10,3))
T = np.roll(triangle.repeat(2,axis=1),-1,axis=1)
T = T.reshape(len(T)*3,2)
T = np.sort(T,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(    0,     0) (    0,     1) (    0,   256) (    0,   257)
 (    0, 65536) (    0, 65537) (    0, 65792) (    0, 65793)
 (    1,     1) (    1,   256) (    1, 65536) (    1, 65537)
 (    1, 65792) (    1, 65793) (  256,     0) (  256,     1)
 (  256,   256) (  256, 65536) (  256, 65537) (  256, 65792)
 (  256, 65793) (  257,     0) (  257,     1) (  257,   256)
 (  257,   257) (  257, 65536) (  257, 65537) (  257, 65792)
 (  257, 65793) (65536,     0) (65536,     1) (65536,   256)
 (65536,   257) (65536, 65536) (65536, 65537) (65536, 65793)
 (65537,     0) (65537,     1) (65537,   256) (65537,   257)
 (65537, 65536) (65537, 65537) (65537, 65792) (65537, 65793)
 (65792,     0) (65792,     1) (65792,   256) (65792,   257)
 (65792, 65536) (65793,     0) (65793,     1) (65793,   256)
 (65793,   257) (65793, 65536) (65793, 65537) (65793, 65792)
 (65793, 65793)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [90]:
c = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(c)), c)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [91]:
def moving_average(a, n=3) :
    r = np.cumsum(a, dtype=float)
    r[n:] = r[n:] - r[:-n]
    return r[n - 1:] / n
Q = np.arange(20)
print(moving_average(Q, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [92]:
from numpy.lib import stride_tricks

def rolling(a, window):
    sh = (a.size - window + 1, window)
    st = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=sh, strides=st)
Q = rolling(np.arange(10), 3)
print(Q)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [95]:
Q = np.random.randint(0,2,100)
np.logical_not(Q, out=Q)

Q = np.random.uniform(-1.0,1.0,100)
np.negative(Q, out=Q)

array([ 0.18521362,  0.44735931, -0.79474754,  0.77481068,  0.42644115,
        0.64931167,  0.04524908, -0.93353177,  0.91018663,  0.39687394,
        0.75322894,  0.10616266,  0.26043723,  0.43105443,  0.43552393,
       -0.80856935,  0.53260474,  0.76712821,  0.86539361, -0.96129332,
       -0.68401361,  0.62312936,  0.20844378,  0.6642682 , -0.27426333,
        0.10343501, -0.35137196, -0.86676175, -0.9571571 ,  0.04343208,
       -0.18944304,  0.72421022, -0.41924753, -0.11482117,  0.1107949 ,
       -0.23035168, -0.89489823, -0.78550489,  0.20097963, -0.33089638,
        0.74917941, -0.89715862,  0.41951132, -0.92083619,  0.28661696,
       -0.05562829,  0.22464373,  0.37241589,  0.60533046, -0.53784893,
        0.67598343, -0.49460977,  0.08044122, -0.57307875,  0.55977755,
        0.01015685, -0.77864797, -0.8834743 ,  0.71077513,  0.26626155,
        0.48641234,  0.88819128, -0.27418756,  0.60391726,  0.8527263 ,
        0.82497667, -0.57044318,  0.10076338, -0.13132696,  0.66

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [101]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[16.33037133  8.00589318  8.88841234  2.2385729   3.12258756  3.87839591
  3.68963071  4.46327556  0.66840545  0.13129718]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [102]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.74353762  1.96376405  7.75021733 15.16540437  3.11070757  0.44478586
   5.44046533  2.4864925   5.1460559   3.77812974]
 [ 0.27239143 11.31109703  5.83599638  5.4264711   5.28752797 10.48412043
   9.37353547  9.66913153  0.48501564  9.65357415]
 [11.18470538  9.11194366  2.51697095 15.90424799  5.5436667   0.11847831
  17.36044915  1.31710908 10.52150112  6.95239841]
 [ 7.62942995  3.66288963  0.8911399   1.90621359 10.17306647 13.66452975
   1.79102034 15.62218231  7.61765218  2.40537398]
 [ 4.19492922  3.6302953   1.28406057  4.91367119  6.97519377 10.71082631
   1.10682916 12.30733003  4.21327239  2.21217102]
 [ 2.10367567  4.8121757   0.33590615  6.2160077   5.41264394  9.47485725
   3.57111468 10.5493249   2.24926124  3.29151294]
 [ 4.86845662  1.74798188  3.07319812  5.15512802  6.99782239 10.40596244
   0.56129961 12.54814144  4.70973625  0.36881074]
 [ 1.74034523 13.22208962  7.57003511  5.86472219  4.53679884 10.1227239
  11.73305004  8.66941728  0.79562526 11.48832058]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [103]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [104]:
Q = np.arange(1,15,dtype=np.uint32)
r = stride_tricks.as_strided(Z,(11,4),(4,4))
print(r)

[[6 3 1 3]
 [3 1 3 6]
 [1 3 6 9]
 [3 6 9 1]
 [6 9 1 5]
 [9 1 5 7]
 [1 5 7 8]
 [5 7 8 4]
 [7 8 4 4]
 [8 4 4 1]
 [4 4 1 7]]


#### 82. Compute a matrix rank (★★★)

In [105]:
Q = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Q)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [109]:
Q = np.random.randint(0,10,50)
print(np.bincount(Q).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [113]:
Q = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Q, shape=(i, j, n, n), strides=Q.strides + Q.strides)
print(C)

[[[[1 1 0]
   [2 3 3]
   [3 2 4]]

  [[1 0 4]
   [3 3 2]
   [2 4 4]]

  [[0 4 4]
   [3 2 1]
   [4 4 0]]

  ...

  [[1 3 1]
   [2 2 3]
   [1 0 3]]

  [[3 1 3]
   [2 3 0]
   [0 3 1]]

  [[1 3 2]
   [3 0 1]
   [3 1 4]]]


 [[[2 3 3]
   [3 2 4]
   [0 4 1]]

  [[3 3 2]
   [2 4 4]
   [4 1 4]]

  [[3 2 1]
   [4 4 0]
   [1 4 4]]

  ...

  [[2 2 3]
   [1 0 3]
   [0 1 0]]

  [[2 3 0]
   [0 3 1]
   [1 0 1]]

  [[3 0 1]
   [3 1 4]
   [0 1 1]]]


 [[[3 2 4]
   [0 4 1]
   [4 0 3]]

  [[2 4 4]
   [4 1 4]
   [0 3 4]]

  [[4 4 0]
   [1 4 4]
   [3 4 0]]

  ...

  [[1 0 3]
   [0 1 0]
   [1 1 4]]

  [[0 3 1]
   [1 0 1]
   [1 4 0]]

  [[3 1 4]
   [0 1 1]
   [4 0 4]]]


 ...


 [[[0 1 0]
   [3 2 4]
   [0 3 1]]

  [[1 0 2]
   [2 4 3]
   [3 1 3]]

  [[0 2 1]
   [4 3 0]
   [1 3 2]]

  ...

  [[4 4 4]
   [3 3 4]
   [2 0 0]]

  [[4 4 4]
   [3 4 3]
   [0 0 0]]

  [[4 4 3]
   [4 3 0]
   [0 0 2]]]


 [[[3 2 4]
   [0 3 1]
   [2 1 3]]

  [[2 4 3]
   [3 1 3]
   [1 3 0]]

  [[4 3 0]
   [1 3 2]
   [3 0 3]]

  ...

  [[3

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [114]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  3 13 12  7]
 [ 3  8  8 13  3]
 [13  8  2 42 10]
 [12 13 42  8  8]
 [ 7  3 10  8  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [115]:
p, n = 10, 20
m = np.ones((p,n,n))
v = np.ones((p,n,1))
s = np.tensordot(m, v, axes=[[0, 2], [0, 1]])
print(s)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [116]:
Q = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Q, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 32.]
 [16. 16. 32.]
 [32. 32. 64.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [340]:
def iterate(Q):
    # Count neighbours
    N = (Q[0:-2,0:-2] + Q[0:-2,1:-1] + Q[0:-2,2:] +
         Q[1:-1,0:-2]                + Q[1:-1,2:] +
         Q[2:  ,0:-2] + Q[2:  ,1:-1] + Q[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Q[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Q[1:-1,1:-1]==1)
    Q[...] = 0
    Q[1:-1,1:-1][birth | survive] = 1
    return Q

Q = np.random.randint(0,2,(50,50))
for i in range(100): Q = iterate(Z)
print(Q)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [118]:
Q = np.arange(10000)
np.random.shuffle(Q)
n = 5

# Slow
print (Q[np.argsort(Q)[-n:]])

# Fast
print (Q[np.argpartition(-Q,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9997 9995 9999 9998]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [119]:
def cartesian(arrays):
    arrs = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrs), -1).T

    for n, arr in enumerate(arrs):
        ix[:, n] = arrs[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [121]:
Q = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
Q = np.core.records.fromarrays(Q.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [122]:
x = np.random.randint(5e4)

%timeit np.power(x,3)
%timeit x*x*x
#%timeit np.einsum('i,i,i->i',x,x,x)

1 µs ± 14.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
117 ns ± 2.83 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [123]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))

c = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [124]:
Q = np.random.randint(0,5,(10,3))
print(Q)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Q[:,:-1], axis=1)
U = Q[~E]
print(U)

[[4 4 1]
 [4 0 3]
 [2 1 4]
 [2 4 3]
 [2 2 0]
 [3 3 4]
 [1 4 4]
 [2 2 0]
 [3 0 1]
 [1 1 0]]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [125]:
i = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
b = ((i.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(b[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [126]:
Q = np.random.randint(0,2,(6,3))
uQ = np.unique(Q, axis=0)
print(uQ)

[[0 0 0]
 [0 1 0]
 [1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [127]:
a = np.random.uniform(0,1,10)
b = np.random.uniform(0,1,10)

np.einsum('i->', a)       # np.sum(A)
np.einsum('i,i->i', a, b) # A * B
np.einsum('i,i', a, b)    # np.inner(A, B)
np.einsum('i,j->ij', a, b)    # np.outer(A, B)

array([[0.74828194, 0.52346   , 0.4016299 , 0.48626478, 0.8720119 ,
        0.45595251, 0.05157327, 0.47815786, 0.84343797, 0.56002813],
       [0.45224112, 0.31636489, 0.24273412, 0.29388512, 0.52702012,
        0.27556522, 0.03116948, 0.28898552, 0.50975082, 0.33846567],
       [0.60479007, 0.42308038, 0.32461264, 0.39301779, 0.70479336,
        0.36851825, 0.04168349, 0.38646546, 0.68169881, 0.45263615],
       [0.21693065, 0.15175366, 0.1164345 , 0.14097058, 0.25280059,
        0.1321829 , 0.01495135, 0.13862034, 0.24451686, 0.16235494],
       [0.26430491, 0.18489428, 0.14186198, 0.17175634, 0.30800827,
        0.16104957, 0.01821649, 0.16889285, 0.29791551, 0.19781072],
       [0.51016705, 0.35688693, 0.27382505, 0.3315278 , 0.59452423,
        0.31086137, 0.03516186, 0.32600063, 0.57504296, 0.38181852],
       [0.67380595, 0.47136039, 0.36165595, 0.43786718, 0.78522116,
        0.41057187, 0.04644022, 0.43056713, 0.75949117, 0.50428892],
       [0.70459979, 0.49290219, 0.3781841

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [130]:
fi = np.arange(0, 10*np.pi, 0.1)
A = 1
X = A*fi*np.cos(fi)
Y = A*fi*np.sin(fi)

dr = (np.diff(X)**2 + np.diff(Y)**2)**.5 # segment lengths
r = np.zeros_like(X)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, X)       # integrate path
y_int = np.interp(r_int, r, Y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [131]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
m = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
m &= (X.sum(axis=-1) == n)
print(X[m])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [133]:
Y = np.random.randn(100) # random 1D array
n = 1000 # number of bootstrap samples
idy = np.random.randint(0, Y.size, (n, Y.size))
means = Y[idy].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.11287876  0.29096973]
